name: CI_IBM

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: dados do diretório
      run: ls -la ../
      run: pwd

    - name: Validando o pacote Java
      run: mvn package -Dmaven.test.skip

  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
    - name: Roda o teste de unidade
      run: mvn test