name: CI_IBM

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Roda um escript shell
      run: echo "Olá git actions"

  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
    - name: Roda um escript shell
      run: echo "Olá git actions"